addons: 
  firefox: "latest"
  apt: 
    sources: 
      - ubuntu-toolchain-r-test 
    packages: 
      - gcc-4.8
      - g++-4.8
      - oracle-java8-set-default
language: node_js
before_install:
  - sudo apt-get install frotz -y
node_js:
  - 8
  - node
before_script:
  - sleep 3
env:
- GOOGLE_FIT_CLIENT_SECRET=GOOGLE_FIT_CLIENT_SECRET GOOGLE_FIT_CLIENT_ID=GOOGLE_FIT_CLIENT_ID MAIN_ADMIN_USERNAME=admin@foo.com CODERUSS_CLIENT_ID=58e4d1ce39e7d8076ddd0ec2 CODERUSS_CLIENT_SECRET=secret ALEXA_CHECK_CERT=0 NODE_ENV=TEST CXX=g++-4.8 EXPRESS_SESSION_SECRET=123 PORT=3000 MONGO_CONNECTION=mongodb://localhost:27017 MONGO_URI=mongodb://localhost:27017
services:
  - mongodb
script:
  - npm run test:travis
  - npm run report:coveralls || true
cache:
  directories:
    - node_modules
