version: '2'
volumes:
  node_modules:
  node_bitbucket_node_modules:
  hackathon_node_modules:
services:
  web:
    container_name: coderuss
    ports:
      - "3000:3000"
      - "27017:27017"
    build: .
    # http://stackoverflow.com/questions/37100358/docker-composer-exited-with-code-0
    tty: true 
    volumes:
      - ..:/coderuss
      - node_modules:/coderuss/node_modules
      - node_bitbucket_node_modules:/coderuss/examples/node-bitbucket/node_modules
      - hackathon_node_modules:/coderuss/examples/hackathon-starter-master/node_modules

#on startup
#mongod &
#cd coderuss
#nodemon nodeserver/server.js